#!/usr/bin/env bash

ROOT_PATH="$(realpath $(dirname ${BASH_SOURCE[0]})/..)"
WEB_PATH="${ROOT_PATH}/www"

DEST_PATH="${WEB_PATH}/assets/scripts/bibli-naheulbeuk.js"

cat \
  "${ROOT_PATH}/node_modules/dom-event-emitter/src/event-emitter.js" \
  "${ROOT_PATH}/node_modules/ajax-download/src/ajax-download.js" \
  "${ROOT_PATH}/node_modules/cg-offline-playback/src/storage.js" \
  "${ROOT_PATH}/node_modules/cg-offline-playback/src/cgop-playlist.js" \
  "${ROOT_PATH}/node_modules/cg-offline-playback/src/cgop-track.js" \
  > "${DEST_PATH}" &&
echo "${DEST_PATH} generated."
