#!/usr/bin/env bash

function confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? (y/N)} " response
    case $response in
        [yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

ROOT_PATH="$(realpath $(dirname ${BASH_SOURCE[0]})/..)"
WEB_PATH="${ROOT_PATH}/www"

confirm "You are about to deploy the code as it is in the '${WEB_PATH}' directory. Confirm? (y/N)" || exit

cd "${ROOT_PATH}" &&
npm install &&
cd - >/dev/null &&
rsync --safe-links --delete --times --human-readable --progress -r "${WEB_PATH}/" naheulbeuk@cguille.net:www/
